-- Pickleball rebrand: remap the pickle-food seed catalog (brands, categories,
-- products, attributes, variants) to pickleball gear. Idempotent: every rename
-- is guarded by NOT EXISTS on the target slug/SKU, so reruns and
-- migrate-then-seed orderings are safe. Order-item snapshots and status history
-- are intentionally left untouched as historical records.
UPDATE "brands" SET "name" = 'Court Thread', "slug" = 'court-thread' WHERE "slug" = 'manila-ferments' AND NOT EXISTS (SELECT 1 FROM "brands" WHERE "slug" = 'court-thread');--> statement-breakpoint
UPDATE "brands" SET "name" = 'Carbon Edge', "slug" = 'carbon-edge' WHERE "slug" = 'sili-lab' AND NOT EXISTS (SELECT 1 FROM "brands" WHERE "slug" = 'carbon-edge');--> statement-breakpoint
UPDATE "categories" SET "name" = 'Pro Paddles', "slug" = 'pro-paddles', "description" = 'Pro-level pickleball paddles' WHERE "slug" = 'classic-dill' AND NOT EXISTS (SELECT 1 FROM "categories" WHERE "slug" = 'pro-paddles');--> statement-breakpoint
UPDATE "categories" SET "name" = 'Paddles', "slug" = 'paddles', "description" = 'Brand-new pickleball paddles for every level', "parent_id" = NULL WHERE "slug" = 'garlic-dill' AND NOT EXISTS (SELECT 1 FROM "categories" WHERE "slug" = 'paddles');--> statement-breakpoint
UPDATE "categories" SET "name" = 'Balls', "slug" = 'balls', "description" = 'Tournament-grade indoor and outdoor pickleballs' WHERE "slug" = 'spicy-sili' AND NOT EXISTS (SELECT 1 FROM "categories" WHERE "slug" = 'balls');--> statement-breakpoint
UPDATE "categories" SET "name" = 'Apparel', "slug" = 'apparel', "description" = 'Court-ready sportswear and apparel' WHERE "slug" = 'sweet-butter' AND NOT EXISTS (SELECT 1 FROM "categories" WHERE "slug" = 'apparel');--> statement-breakpoint
UPDATE "categories" SET "name" = 'Accessories', "slug" = 'accessories', "description" = 'Grips, bags, caps and court essentials' WHERE "slug" = 'fermented-favorites' AND NOT EXISTS (SELECT 1 FROM "categories" WHERE "slug" = 'accessories');--> statement-breakpoint
-- Attribute renames, scoped by old product slug (products still carry old slugs here).
UPDATE "product_attributes" pa SET "name" = 'Grip' FROM "products" p WHERE pa."product_id" = p."id" AND p."slug" = 'classic-dill-pickles' AND pa."name" = 'Size';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = '4"' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'classic-dill-pickles' AND pa."name" = 'Grip' AND pav."value" = '250ml';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = '4.25"' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'classic-dill-pickles' AND pa."name" = 'Grip' AND pav."value" = '500ml';--> statement-breakpoint
UPDATE "product_attributes" pa SET "name" = 'Grip' FROM "products" p WHERE pa."product_id" = p."id" AND p."slug" = 'spicy-dill-pickles' AND pa."name" = 'Size';--> statement-breakpoint
UPDATE "product_attributes" pa SET "name" = 'Weight' FROM "products" p WHERE pa."product_id" = p."id" AND p."slug" = 'spicy-dill-pickles' AND pa."name" = 'Heat';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = '4"' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'spicy-dill-pickles' AND pa."name" = 'Grip' AND pav."value" = '250ml';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = '4.25"' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'spicy-dill-pickles' AND pa."name" = 'Grip' AND pav."value" = '500ml';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = 'Light' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'spicy-dill-pickles' AND pa."name" = 'Weight' AND pav."value" = 'Medium';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = 'Standard' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'spicy-dill-pickles' AND pa."name" = 'Weight' AND pav."value" = 'Hot';--> statement-breakpoint
UPDATE "product_attributes" pa SET "name" = 'Grip' FROM "products" p WHERE pa."product_id" = p."id" AND p."slug" = 'kimchi-style-mustasa' AND pa."name" = 'Size';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = '4"' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'kimchi-style-mustasa' AND pa."name" = 'Grip' AND pav."value" = '250ml';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = '4.25"' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'kimchi-style-mustasa' AND pa."name" = 'Grip' AND pav."value" = '500ml';--> statement-breakpoint
-- Socks product (ex-jalapeno): drop the old Size subtree, then Heat -> Size.
DELETE FROM "variant_attribute_values" vav USING "product_attribute_values" pav, "product_attributes" pa, "products" p WHERE vav."attribute_value_id" = pav."id" AND pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'jalapeno-nacho-slices' AND pa."name" = 'Size';--> statement-breakpoint
DELETE FROM "product_attribute_values" pav USING "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'jalapeno-nacho-slices' AND pa."name" = 'Size';--> statement-breakpoint
DELETE FROM "product_attributes" pa USING "products" p WHERE pa."product_id" = p."id" AND p."slug" = 'jalapeno-nacho-slices' AND pa."name" = 'Size';--> statement-breakpoint
UPDATE "product_attributes" pa SET "name" = 'Size' FROM "products" p WHERE pa."product_id" = p."id" AND p."slug" = 'jalapeno-nacho-slices' AND pa."name" = 'Heat';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = 'M' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'jalapeno-nacho-slices' AND pa."name" = 'Size' AND pav."value" = 'Medium';--> statement-breakpoint
UPDATE "product_attribute_values" pav SET "value" = 'L' FROM "product_attributes" pa, "products" p WHERE pav."attribute_id" = pa."id" AND pa."product_id" = p."id" AND p."slug" = 'jalapeno-nacho-slices' AND pa."name" = 'Size' AND pav."value" = 'Hot';--> statement-breakpoint
-- Variant SKU/name/price remaps.
UPDATE "product_variants" SET "sku" = 'PADDLE-VOLT-400', "name" = '4"', "price_override" = NULL WHERE "sku" = 'PICKLE-DILL-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-VOLT-400');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-VOLT-425', "name" = '4.25"', "price_override" = 569900 WHERE "sku" = 'PICKLE-DILL-500' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-VOLT-425');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-SURGE-400', "price_override" = NULL WHERE "sku" = 'DILL-GARLIC-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-SURGE-400');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'BALL-TOUR-OUT-3PK', "price_override" = NULL WHERE "sku" = 'SILI-LABUYO-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'BALL-TOUR-OUT-3PK');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'APPAREL-TEE-M', "price_override" = NULL WHERE "sku" = 'SWEET-BB-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'APPAREL-TEE-M');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'APPAREL-SHORTS-M', "price_override" = NULL WHERE "sku" = 'ATCHARA-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'APPAREL-SHORTS-M');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-CTRL-LT-400', "name" = 'Light / 4"', "price_override" = NULL WHERE "sku" = 'SPICY-DILL-MED-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-CTRL-LT-400');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-CTRL-STD-400', "name" = 'Standard / 4"', "price_override" = NULL WHERE "sku" = 'SPICY-DILL-HOT-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-CTRL-STD-400');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-CTRL-STD-425', "name" = 'Standard / 4.25"', "price_override" = 519900 WHERE "sku" = 'SPICY-DILL-HOT-500' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-CTRL-STD-425');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-RALLY-400', "name" = '4"', "price_override" = NULL WHERE "sku" = 'MUSTASA-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-RALLY-400');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'PADDLE-RALLY-425', "name" = '4.25"', "price_override" = 259900 WHERE "sku" = 'MUSTASA-500' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'PADDLE-RALLY-425');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'APPAREL-CAP-OS', "price_override" = NULL WHERE "sku" = 'ONION-RED-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'APPAREL-CAP-OS');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'BALL-TOUR-OUT-6PK', "price_override" = NULL WHERE "sku" = 'MANGGA-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'BALL-TOUR-OUT-6PK');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'APPAREL-SOCKS-M', "name" = 'M', "price_override" = NULL WHERE "sku" = 'JAL-MED-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'APPAREL-SOCKS-M');--> statement-breakpoint
UPDATE "product_variants" SET "sku" = 'APPAREL-SOCKS-L', "name" = 'L', "price_override" = NULL WHERE "sku" = 'JAL-HOT-250' AND NOT EXISTS (SELECT 1 FROM "product_variants" WHERE "sku" = 'APPAREL-SOCKS-L');--> statement-breakpoint
-- Surplus third jalapeno variant has no counterpart in the new catalog: archive it.
UPDATE "product_variants" SET "status" = 'archived', "is_active" = false WHERE "sku" = 'JAL-HOT-500';--> statement-breakpoint
-- Product renames + fields (prices/descriptions now match the new seed).
UPDATE "products" SET "name" = 'Volt Pro Carbon Paddle', "slug" = 'volt-pro-carbon-paddle', "description" = 'Seeded pro carbon pickleball paddle', "base_price" = 549900 WHERE "slug" = 'classic-dill-pickles' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'volt-pro-carbon-paddle');--> statement-breakpoint
UPDATE "products" SET "name" = 'Surge Fiberglass Paddle', "slug" = 'surge-fiberglass-paddle', "short_description" = 'Lightweight fiberglass paddle', "description" = 'Lightweight fiberglass paddle with a comfort grip', "sku" = 'PADDLE-SURGE-400', "base_price" = 349900, "compare_price" = 419900, "cost_price" = 180000, "low_stock_threshold" = 10, "weight_g" = 230 WHERE "slug" = 'garlic-dill-spears' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'surge-fiberglass-paddle');--> statement-breakpoint
UPDATE "products" SET "name" = 'Tour Outdoor Balls 3-Pack', "slug" = 'tour-outdoor-balls-3pk', "short_description" = 'Tournament outdoor balls', "description" = 'Tournament-grade 40-hole outdoor pickleballs, 3-pack', "sku" = 'BALL-TOUR-OUT-3PK', "base_price" = 59900, "compare_price" = 74900, "cost_price" = 25000, "low_stock_threshold" = 5, "weight_g" = 300 WHERE "slug" = 'siling-labuyo-pickles' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'tour-outdoor-balls-3pk');--> statement-breakpoint
UPDATE "products" SET "name" = 'Dry-Fit Court Tee', "slug" = 'dry-fit-court-tee', "short_description" = 'Sweat-wicking court tee', "description" = 'Sweat-wicking dry-fit tee for long court sessions', "sku" = 'APPAREL-TEE-M', "base_price" = 129900, "compare_price" = NULL, "cost_price" = NULL, "weight_g" = 180 WHERE "slug" = 'sweet-butter-chips' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'dry-fit-court-tee');--> statement-breakpoint
UPDATE "products" SET "name" = 'Court Performance Shorts', "slug" = 'court-performance-shorts', "short_description" = 'Classic court shorts', "description" = 'Lightweight performance shorts with ball pockets', "sku" = 'APPAREL-SHORTS-M', "base_price" = 139900, "cost_price" = 60000, "weight_g" = 220 WHERE "slug" = 'atchara-papaya-relish' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'court-performance-shorts');--> statement-breakpoint
UPDATE "products" SET "name" = 'Control Touch Pro Paddle', "slug" = 'control-touch-pro-paddle', "short_description" = 'Control paddle with spin texture', "description" = 'Carbon-face control paddle with spin texture', "base_price" = 499900, "compare_price" = 579900, "cost_price" = 250000, "weight_g" = 235 WHERE "slug" = 'spicy-dill-pickles' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'control-touch-pro-paddle');--> statement-breakpoint
UPDATE "products" SET "name" = 'Rally Starter Paddle', "slug" = 'rally-starter-paddle', "short_description" = 'Beginner-friendly paddle', "description" = 'Beginner-friendly paddle with a wide sweet spot', "base_price" = 249900, "cost_price" = 120000, "weight_g" = 240 WHERE "slug" = 'kimchi-style-mustasa' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'rally-starter-paddle');--> statement-breakpoint
UPDATE "products" SET "name" = 'Sideline Court Cap', "slug" = 'sideline-court-cap', "short_description" = 'Breathable court cap', "description" = 'Breathable one-size court cap', "sku" = 'APPAREL-CAP-OS', "base_price" = 89900, "cost_price" = 35000, "weight_g" = 100 WHERE "slug" = 'pickled-red-onions' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'sideline-court-cap');--> statement-breakpoint
UPDATE "products" SET "name" = 'Tour Outdoor Balls 6-Pack', "slug" = 'tour-outdoor-balls-6pk', "short_description" = 'Outdoor balls value pack', "description" = 'Tournament-grade outdoor pickleballs, value 6-pack', "sku" = 'BALL-TOUR-OUT-6PK', "base_price" = 99900, "compare_price" = 119900, "cost_price" = 45000, "low_stock_threshold" = 5, "weight_g" = 550 WHERE "slug" = 'burong-mangga' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'tour-outdoor-balls-6pk');--> statement-breakpoint
UPDATE "products" SET "name" = 'Court Cushion Socks 3-Pack', "slug" = 'court-cushion-socks-3pk', "short_description" = 'Cushioned court socks', "description" = 'Cushioned ankle socks for quick lateral moves', "base_price" = 79900, "cost_price" = 30000, "weight_g" = 150 WHERE "slug" = 'jalapeno-nacho-slices' AND NOT EXISTS (SELECT 1 FROM "products" WHERE "slug" = 'court-cushion-socks-3pk');--> statement-breakpoint
-- Product images: point placeholder URLs/alts at the new slugs.
UPDATE "product_images" SET "url" = REPLACE("url", 'classic-dill-pickles', 'volt-pro-carbon-paddle'), "alt" = 'Volt Pro Carbon Paddle' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'volt-pro-carbon-paddle');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'garlic-dill-spears', 'surge-fiberglass-paddle'), "alt" = 'Surge Fiberglass Paddle' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'surge-fiberglass-paddle');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'siling-labuyo-pickles', 'tour-outdoor-balls-3pk'), "alt" = 'Tour Outdoor Balls 3-Pack' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'tour-outdoor-balls-3pk');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'sweet-butter-chips', 'dry-fit-court-tee'), "alt" = 'Dry-Fit Court Tee' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'dry-fit-court-tee');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'atchara-papaya-relish', 'court-performance-shorts'), "alt" = 'Court Performance Shorts' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'court-performance-shorts');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'spicy-dill-pickles', 'control-touch-pro-paddle'), "alt" = 'Control Touch Pro Paddle' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'control-touch-pro-paddle');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'kimchi-style-mustasa', 'rally-starter-paddle'), "alt" = 'Rally Starter Paddle' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'rally-starter-paddle');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'pickled-red-onions', 'sideline-court-cap'), "alt" = 'Sideline Court Cap' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'sideline-court-cap');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'burong-mangga', 'tour-outdoor-balls-6pk'), "alt" = 'Tour Outdoor Balls 6-Pack' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'tour-outdoor-balls-6pk');--> statement-breakpoint
UPDATE "product_images" SET "url" = REPLACE("url", 'jalapeno-nacho-slices', 'court-cushion-socks-3pk'), "alt" = 'Court Cushion Socks 3-Pack' WHERE "product_id" IN (SELECT "id" FROM "products" WHERE "slug" = 'court-cushion-socks-3pk');--> statement-breakpoint
-- Promo copy.
UPDATE "promotions" SET "name" = 'Seed 20% Paddle Line', "description" = '20% off seed paddle lines' WHERE "name" = 'Seed 20% Pickle Line' AND NOT EXISTS (SELECT 1 FROM "promotions" WHERE "name" = 'Seed 20% Paddle Line');--> statement-breakpoint
UPDATE "promotions" SET "name" = 'Seed BOGO Balls', "description" = 'Buy 2 get 1 free (tour outdoor 3-pack)' WHERE "name" = 'Seed BOGO Pickle' AND NOT EXISTS (SELECT 1 FROM "promotions" WHERE "name" = 'Seed BOGO Balls');--> statement-breakpoint
UPDATE "promotions" SET "description" = '₱100 off pickleball gear lines' WHERE "name" = 'Seed Welcome Code' AND "description" = '₱100 off pickle product lines';--> statement-breakpoint
-- Demo Gold member price follows the renamed ball variant (seed value 29900 -> 49900).
UPDATE "member_prices" SET "price" = 49900 WHERE "price" = 29900 AND "variant_id" IN (SELECT "id" FROM "product_variants" WHERE "sku" = 'BALL-TOUR-OUT-3PK');--> statement-breakpoint
-- Seed customer display name.
UPDATE "users" SET "name" = 'Pickleball Customer' WHERE "email" = 'customer@example.ph' AND "name" = 'Pickle Customer';
